[package]
name = "wrapper"
version = "0.1.0"
edition = "2018"

[dependencies]
dirs = "3.0"
glob = "0.3.0"
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"
env_logger = "0.9"
log = "0.4"
winlog = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"