name: windows_build

on:
  push:
    branches: 'main'

jobs:
  windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2

      - name: Install WixToolset
        run: |
          curl https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip -Lo wix.zip
          mkdir -p wix
          unzip wix.zip -d wix
        shell: bash

      - name: Download dependencies
        run: ./download.sh
        shell: bash

      - name: Build the Rust installer
        run: cd installer && cargo build --release && cp target/release/installer.exe ..
        shell: bash

      - name: Package bundle
        run: |
          wix/candle.exe smauglys.wxs -ext WixBalExtension
          wix/light.exe smauglys.wixobj -ext WixBalExtension
        shell: bash

      - name: Create release tag
        shell: bash
        run: echo "TAG_NAME=$(date +v-%Y-%m-%d-%H%M)" >> $GITHUB_ENV

      - name: Move/rename build artifacts
        run: |
          mv smauglys.exe Smauglys-${TAG_NAME}.exe
        shell: bash

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ./Smauglys-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
