[package]
name = "installer"
version = "0.1.0"
edition = "2018"

[dependencies]
which = "4.2.2"
winlog = "0.2"
native-windows-gui = "1.0.12"
native-windows-derive = "1.0.3"
log = "0.4"
tempfile = "3"
zip = "0.5"
zip-extensions = "0.6"